### ISSUE TITLE
Config should throw ConfigExceptions, not ApiExceptions

### ISSUE THREAD

**Issue by darrynten** [darrynten/sage-one-php#24]
## Overview

| Q                    | A
| -------------------- | ---
| Bug?                 | no
| Feature Request?     | no
| Enhancement?         | yes
| Documentation issue? | no
| Version?             | -
| Related issues?      | -

## What happened?

The Config class is throwing ApiExceptions

## What should have happened?

The Config class should throw ConfigExceptions

**Comment by fergusdixon** [comment]
Fixed in PR #69
