### ISSUE TITLE
Some Models are missing tests

### ISSUE THREAD

**Issue by darrynten** [darrynten/sage-one-php#34]
## Overview

| Q                    | A
| -------------------- | ---
| Bug?                 | yes
| Feature Request?     | yes
| Enhancement?         | yes
| Documentation issue? | yes
| Version?             | -
| Related PR?      | #32 

## What happened?

We're putting some code in without tests to keep the PR smaller

These are Customer, AdditionalPriceList, CustomerCategory, SalesRepresentative, TaxInvoice

## What should have happened?

These models need tests

## Which steps would reproduce this problem?

You will see the files are not present in the test folder

## Additional Information

The tests are still passing as the base model is abstract, so we need defensive tests in place to ensure the classes always stay as they should be

Alert the following people: @igorsergiichuk @cheynecaleb @fergusdixon @KaroZA

**Comment by make-it-git** [comment]
I'll take this
