### ISSUE TITLE
Customer Model missing support for `inludeSalesRepDetails` `all()` call

### ISSUE THREAD

**Issue by darrynten** [darrynten/sage-one-php#42]
## Overview

| Q                    | A
| -------------------- | ---
| Bug?                 | no
| Feature Request?     | yes
| Enhancement?         | yes
| Documentation issue? | no
| Version?             | -
| Related issues?      | -
| Related PR?      | #37 

## What happened?

Customer model supports additional GET parameter called `includeSalesRepDetails` with its `all()` call.

[Related PR, Line, and File](https://github.com/darrynten/sage-one-php/pull/39/files#diff-5f004168b647f5a14208dd7727a73fe0R373)

Support for this additional variable needs to be added

**Comment by make-it-git** [comment]
Fixed in https://github.com/darrynten/sage-one-php/pull/48
