### ISSUE TITLE
Additional regex checks

### ISSUE THREAD

**Issue by darrynten** [darrynten/sage-one-php#43]
## Overview

| Q                    | A
| -------------------- | ---
| Bug?                 | no
| Feature Request?     | yes
| Enhancement?         | yes
| Documentation issue? | yes
| Version?             | -
| Related PR?      | #37 

## What happened?

SageOne has an email validation regex on one of their documentation pages, but do not have it elsewhere.

Proposal is to add the regex check for all email fields, and add additional defensive regex checks against things like guids.

## Additional Information

Enhancement that is out of scope for initial deliverable

**Comment by make-it-git** [comment]
https://github.com/darrynten/sage-one-php/pull/47
