### ISSUE TITLE
Implement AnalysisCategory and AnalysisType models

### ISSUE THREAD

**Issue by make-it-git** [darrynten/sage-one-php#52]
## Overview

| Q                    | A
| -------------------- | ---
| Bug?                 | no
| Feature Request?     | yes
| Enhancement?         | yes
| Documentation issue? | no

https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_AnalysisCategory
https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_AnalysisType

...

Alert the following people: @darrynten

**Comment by fergusdixon** [comment]
Both models have been added
