### ISSUE TITLE
Implement Company, CompanyEntityType and CompanyNote models

### ISSUE THREAD

**Issue by make-it-git** [darrynten/sage-one-php#53]
## Overview

| Q                    | A
| -------------------- | ---
| Bug?                 | no
| Feature Request?     | yes
| Enhancement?         | yes
| Documentation issue? | no

https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_Company
https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_CompanyEntityType
https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_CompanyNote

...

Alert the following people: @darrynten

**Comment by fergusdixon** [comment]
#74

**Comment by fergusdixon** [comment]
#74 Completes this request
