### ISSUE TITLE
Implement AccountBalance and AccountNoteAttachment models

### ISSUE THREAD

**Issue by make-it-git** [darrynten/sage-one-php#54]
## Overview

| Q                    | A
| -------------------- | ---
| Bug?                 | no
| Feature Request?     | yes
| Enhancement?         | yes
| Documentation issue? | no

https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_AccountBalance
https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_AccountNoteAttachment

...

Alert the following people: @darrynten

**Comment by darrynten** [comment]
@make-it-git I think this is resolved now?
