### ISSUE TITLE
Implement SupplierAdditionalContactDetail, SupplierAgeing, SupplierPurchaseHistory and SupplierStatement models

### ISSUE THREAD

**Issue by make-it-git** [darrynten/sage-one-php#55]
## Overview

| Q                    | A
| -------------------- | ---
| Bug?                 | no
| Feature Request?     | yes
| Enhancement?         | yes
| Documentation issue? | no

https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_SupplierAdditionalContactDetail
https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_SupplierAgeing
https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_SupplierPurchaseHistory
https://accounting.sageone.co.za/api/1.1.2/Help#bookmark_SupplierStatement

...

Alert the following people: @darrynten

**Comment by kiproping** [comment]
I am currently working on supplierAgeing and purchaseHistory

**Comment by darrynten** [comment]
This issue is resolved! 😎🎉
